<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Monitor.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Monitor.Domain\Monitor.Domain.csproj" />
    <ProjectReference Include="..\Monitor.Infrastructure\Monitor.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="OtlpProtos\**\*.proto" ProtoRoot="OtlpProtos" GrpcServices="None" />
    <Protobuf Update="OtlpProtos\opentelemetry\proto\collector\trace\v1\trace_service.proto" GrpcServices="Both" />
    <Protobuf Update="OtlpProtos\opentelemetry\proto\collector\logs\v1\logs_service.proto" GrpcServices="Both" />
    <Protobuf Update="OtlpProtos\opentelemetry\proto\collector\metrics\v1\metrics_service.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
